# Generated by Django 5.2.4 on 2025-07-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_name", models.CharField(db_column="name", max_length=255)),
                ("_ects_points", models.IntegerField(db_column="ects_points")),
                ("_expected_hours", models.FloatField(db_column="expected_hours")),
                (
                    "_bg_color",
                    models.CharField(
                        db_column="bg_color", default="#000000", max_length=7
                    ),
                ),
                (
                    "_fg_color",
                    models.CharField(
                        db_column="fg_color", default="#ffffff", max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_name", models.CharField(db_column="name", max_length=255)),
                ("_ects_goal", models.IntegerField(db_column="ects_goal")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "_first_name",
                    models.CharField(db_column="first_name", max_length=100),
                ),
                ("_last_name", models.CharField(db_column="last_name", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_name", models.CharField(db_column="name", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_spent_hours", models.FloatField(db_column="spent_hours", default=0)),
                (
                    "_completed",
                    models.BooleanField(db_column="completed", default=False),
                ),
                (
                    "_course",
                    models.ForeignKey(
                        db_column="course",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.course",
                    ),
                ),
                (
                    "_student",
                    models.ForeignKey(
                        db_column="student",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="_degree",
            field=models.ForeignKey(
                db_column="degree",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.degree",
            ),
        ),
        migrations.CreateModel(
            name="ExamOutcome",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_grade", models.FloatField(db_column="grade")),
                ("_passed", models.BooleanField(db_column="passed", default=False)),
                (
                    "_course_registration",
                    models.ForeignKey(
                        db_column="course_registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.courseregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_name", models.CharField(db_column="name", max_length=255)),
                ("_number", models.IntegerField(db_column="number")),
                (
                    "_degree",
                    models.ForeignKey(
                        db_column="degree",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.degree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSemester",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "_course",
                    models.ForeignKey(
                        db_column="course",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.course",
                    ),
                ),
                (
                    "_semester",
                    models.ForeignKey(
                        db_column="semester",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDegree",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_start_date", models.DateField(db_column="start_date")),
                ("_end_date", models.DateField(db_column="end_date")),
                ("_ects_collected", models.IntegerField(db_column="ects_collected")),
                (
                    "_degree",
                    models.ForeignKey(
                        db_column="degree",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.degree",
                    ),
                ),
                (
                    "_student",
                    models.ForeignKey(
                        db_column="student",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimePlanBooking",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("_from_date", models.DateField(db_column="from_date")),
                ("_from_time", models.TimeField(db_column="from_time")),
                ("_until_date", models.DateField(db_column="until_date")),
                ("_until_time", models.TimeField(db_column="until_time")),
                (
                    "_course_registration",
                    models.ForeignKey(
                        db_column="course_registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.courseregistration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="_university",
            field=models.ForeignKey(
                db_column="university",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.university",
            ),
        ),
        migrations.AddField(
            model_name="degree",
            name="_university",
            field=models.ForeignKey(
                db_column="university",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.university",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="_university",
            field=models.ForeignKey(
                db_column="university",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dashboard.university",
            ),
        ),
    ]
